#ifndef SERIALREADERDLL_GLOBAL_H
#define SERIALREADERDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALREADERDLL_LIBRARY)
#  define SERIALREADERDLL_EXPORT Q_DECL_EXPORT
#else
#  define SERIALREADERDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALREADERDLL_GLOBAL_H
